export default {
  en:{
    ACCOUNT:'Account',
    ADD_GROUP_MESSAGE:'Input new favorite group name',
    ADD_KEEP:'Keep it',
    ADD_APP_SHORTCUT:'Add app shortcut',
    AGGREGATE_DESTS:'Aggregate destinations',
    ALWAYS_ON_TOP:'Toggle always on top',
    APPLY:'Apply',
    ASCEND:'Ascend',
    ATTACH_FILE_LIMIT:'Up to 5 attachments',
    ATTACH_SIZE_LIMIT:'Up to 15 MB in size',
    BOOT_APP:'Boot',
    CANCEL:'Cancel',
    CHANGE_PASSWORD:'Change password',
    CLOSE:'Close',
    CLEAR_FILTER:'Clear message filter',
    CONFIRM_PASSWORD:'Confirm password',
    CONFIRM_REVOKE:'Revoke OK?',
    CONNECTED:'Connected',
    COMPLETED_CHANGE_PASSWORD:'Completed change password',
    CURRENT_PASSWORD:'Current password',
    DISABLED:'Disabled',
    DISCONNECTED:'Disconnected',
    DEPART:'Department',
    DESCEND:'Descend',
    DETAIL:'Detail',
    DWONLOAD_DIR:'File download directory',
    EN:'English',
    EXIT:'Exit',
    ENABLED:'Enabled',
    FILTER_UNREAD:'Filter unread on/off',
    FILTER_TEAM_NAME:'Filter by team name',
    FILTER:'Filter',
    FILTER_IMPORTANT:'Filter important on/off',
    FOLDTHIS:'Fold',
    FOLD:'Fold/Unfold',
    FOLD_ALL:'Fold all',
    FONT_SIZE:'Font size',
    GROUP_UPDATED:'Group updated',
    HELP:'Help',
    HIDE_IMG:'Hide img',
    IDLE:'Leaving',
    INPUT_NOT_ENOUGTH:'Input account and password first.',
    INSERT_CODE:'Insert code',
    INSTALLED:'Installed',
    INSTALL:'Install',
    JA:'Japanese',
    LANGUAGE:'Language',
    LARGE:'Large',
    LARGEST:'Largest',
    LOGIN:'Login',
    LOGIN_FAILED:'Login failed.\nNo registed or invalid password',
    LOST_CONNECTION:'Connection losted',
    MAIL:'Mail address', 
    MENU:'Menu',
    MIDDLE:'Middle',
    MINIMIZE:'Minimize',
    MESSAGE:'Message',
    MOVE_TO_UNREAD:'Move to unread',
    NEW_PASSWORD:'New password',
    NICKNAME:'Nickname',
    NOTIFY_UNREAD:'There are %s unread messages',
    OPEN_DOWNLOAD_DIR:'Open download dir',
    OPEN_APP_STORE:'Open Telepath AppStore',
    OPEN_APP_ROOT:'Choose app package.json',
    OPEN_DIRECT:'Open direct',
    PASSWORD:'Password',
    PASSWORD_UNMATCH:'Unmatch password',
    PERSONAL_INFO_CAUTION:'These informations can be visible by other Telepath users.',
    PERSONAL_INFO:'Register personal info',
    PREVENT_NOTIFY:'Prevent notify',
    READ:'R',
    READ_ALL:'Read All',
    READ_FILTERED:'Reads filtered',
    READ_THIS:'Read',
    READ_THIS_THREAD:'Read this thread',
    RECOMMENDED:'Recommended',
    REMOVE_FAVORITE:'Delete',
    REMOVE_KEEP_CONFIRM:'Remove this keep message ok?',
    REMOVE_APP_SHORTCUT:'Remove app shortcut',
    REPLAY:'Replay',
    REPLY:'Reply',
    REQUEST_ASSIST:'Request remote assistance',
    REQUIRE_MESSAGE:'Require message content',
    REQUIRE_NAME:'Require any name',
    RESET_FAVORITE:'Reset to now selected',
    REVOKED:'This message has been revoked',
    REVOKE_MESSAGE:'Revoke this message',
    SAVE:'Save',
    SAVE_LOGIN:'Save Account',
    SET_IMPORTANT:'Set Important',
    SET_APP_AUTOBOOT:'Set auto boot',
    UNSET_APP_AUTOBOOT:'Unset auto boot',
    TEAM_ORDER:'Team display order',
    TEAM_ORDER_EXP:'Set order of teams as the left list by drag and drop and push the Set button.',
    UNSET_IMPORTANT:'Unset Important',
    FILTER_MESSAGE:'Filter message',
    FILTERED_BY_TEXT:'Filtered by text',
    SEARCH_ON_ENTER:'Search on Enter',
    SELECT_IT:'Select',
    SELECT_TEAM:'Select at least one team',
    SEND:'Send',
    SET:'Set',
    SETTING:'Setting',
    SET_FAVORITE_GROUP:'Create a favorite',
    SET_NEW_PASSWORD:'Set new password',
    SHALLWIN_NOT_FOUND:'Shallwin not found',
    SHOW_ALL:'Show All',
    SHOW_KEEPS:'Show my Keeps',
    SHOW_MESSAGE_DETAIL:'Show this message detail',
    SHOW_TEAM_DETAIL:'Show this team detail',
    SMALL:'Small',
    SMALLEST:'Smallest',
    SORT_ORDER:'Messages sort order',
    START_SHALLWIN:'Start shallwin meeting',
    SUCH_MESSAGE_NOT_FOUND:'Such message not found',
    TEAMS:'teams',
    TEAM_FILTER:'Team filter',
    TEL_NO:'Telephone No.',
    TELEPATH_UPDATED:'The new version will be available to use when you start Telepath next time.',
    THEME:'Theme',
    THREAD:'Thread',
    TOO_SHORT_PASSWORD:'Too short password.',
    TOGGLE_MENU:'Toggle this menu',
    UNREAD_MESSAGE:'%s Unread(s)',
    UNREAD_NOT_EXISTS:'Unread not exists',
    UNSELECT_AFTER_SEND:'Unselect after send',
    UNSELECT_ALL:'Unselect all',
    UNINSTALL:'Uninstall',
    UPDATE:'Update telepath',
    PASS_CONFIRM_NOT_MATCH :'Password and confirm password are not match',
    USER_ICON:'Your icon'
  },
  ja:{
    ACCOUNT:'アカウント',
    ADD_GROUP_MESSAGE:'設定するお気に入りの名前を入力',
    ADD_KEEP:'Keepする',
    ADD_APP_SHORTCUT:'アプリショートカットに追加',
    AGGREGATE_DESTS:'宛先名の集約表示',
    ALWAYS_ON_TOP:'常に前面表示',
    APPLY:'適用',
    ASCEND:'昇順',
    ATTACH_FILE_LIMIT:'添付ファイルは5個まで',
    ATTACH_SIZE_LIMIT:'添付ファイルは合計15MBまで',
    BOOT_APP:'起動',
    CANCEL:'キャンセル',
    CLOSE:'閉じる',
    CHANGE_PASSWORD:'パスワード変更',
    CLEAR_FILTER:'メッセージフィルタを解除',
    CONFIRM_PASSWORD:'確認パスワード',
    CONFIRM_REVOKE:'このメッセージを取消します',
    CONNECTED:'接続中',
    COMPLETED_CHANGE_PASSWORD:'パスワードの変更完了',
    CURRENT_PASSWORD:'現在のパスワード',
    DESCEND:'降順',
    DEPART:'所属部署',
    DISABLED:'無効',
    DISCONNECTED:'未接続',
    DETAIL:'詳細',
    DWONLOAD_DIR:'ダウンロードフォルダ',
    EN:'英語',
    ENABLED:'有効',
    EXIT:'終了',
    FILTER:'フィルタ',
    FILTER_UNREAD:'未読のみ表示 on/off',
    FILTER_TEAM_NAME:'チーム名でフィルタする',
    FILTER_IMPORTANT:'重要のみ表示 on/off',
    FILTERED_BY_TEXT:'文字列でフィルタされています',
    FOLDTHIS:'たたむ',
    FOLD:'たたむ/展開する',
    FOLD_ALL:'全てたたむ',
    FONT_SIZE:'フォントサイズ',
    GROUP_UPDATED:'グループが更新されました',
    HELP:'ヘルプ',
    HIDE_IMG:'画像を非表示',
    IDLE:'離席中',
    INPUT_NOT_ENOUGTH:'アカウントとパスワードを入れてください',
    INSERT_CODE:'コードの挿入',
    INSTALLED:'インストール済',
    INSTALL:'インストール',
    JA:'日本語',
    LANGUAGE:'言語',
    LARGE:'大',
    LARGEST:'最大',
    LOGIN:'ログイン',
    LOGIN_FAILED:'ログイン失敗\nユーザが登録されていないか、パスワードが間違っています',
    LOST_CONNECTION:'サーバとのコネクションが失われています',
    MAIL:'メールアドレス', 
    MENU:'メニュー',
    MIDDLE:'中',
    MESSAGE:'メッセージ',
    MINIMIZE:'最小化',
    MOVE_TO_UNREAD:'次の未読へ移動',
    NEW_PASSWORD:'パスワード',
    NICKNAME:'ニックネーム',
    NOTIFY_UNREAD:'%s 件の未読があります',
    OPEN_DOWNLOAD_DIR:'ﾀﾞｳﾝﾛｰﾄﾞﾌｫﾙﾀﾞ',
    OPEN_APP_STORE:'テレパスAppStoreを開く',
    OPEN_APP_ROOT:'アプリケーションのpackage.jsonを選択',
    OPEN_DIRECT:'直接開く',
    PASSWORD:'パスワード',
    PASSWORD_UNMATCH:'パスワード不一致',
    PERSONAL_INFO_CAUTION:'この入力情報は他のユーザから参照出来る様になります',
    PERSONAL_INFO:'個人情報設定',
    PREVENT_NOTIFY:'新着メッセージ通知抑制',
    READ:'読',
    READ_ALL:'全て既読',
    READ_FILTERED:'既読がフィルタされています',
    READ_THIS:'既読にする',
    READ_THIS_THREAD:'スレッドを全て既読にする',
    RECOMMENDED:'おすすめ',
    REMOVE_FAVORITE:'削除',
    REMOVE_KEEP_CONFIRM:'このキープメッセージを削除します',
    REMOVE_APP_SHORTCUT:'ショートカットから削除します',
    REPLAY:'リプレイ',
    REPLY:'返信',
    REQUEST_ASSIST:'リモートアシストを依頼',
    REQUIRE_MESSAGE:'メッセージ内容が必要',
    REQUIRE_NAME:'名前が必要',
    RESET_FAVORITE:'現在の選択チームを設定',
    REVOKED:'このメッセージは取り消されました',
    REVOKE_MESSAGE:'このメッセージを取り消す',
    SAVE:'保存',
    SAVE_LOGIN:'アカウントを保存',
    SET_IMPORTANT:'重要に設定',
    SET_APP_AUTOBOOT:'自動起動設定',
    UNSET_APP_AUTOBOOT:'自動起動解除',
    TEAM_ORDER:'チーム表示順',
    TEAM_ORDER_EXP:'ドラッグアンドドロップで左のリストにチームの順番を設定し「設定」ボタンを押して確定します',
    UNSET_IMPORTANT:'重要を解除',
    FILTER_MESSAGE:'メッセージフィルタ',
    SEARCH_ON_ENTER:'Enterで検索',
    SELECT_IT:'選択',
    SELECT_TEAM:'最低一つのチームを選択',
    SEND:'送る',
    SET:'設定',
    SETTING:'設定',
    SET_FAVORITE_GROUP:'お気に入りを設定',
    SET_NEW_PASSWORD:'パスワードの初期設定',
    SHALLWIN_NOT_FOUND:'Shallwinが見つかりません',
    SHOW_ALL:'全てみる',
    SHOW_KEEPS:'Keepを表示',
    SHOW_MESSAGE_DETAIL:'メッセージ詳細',
    SHOW_TEAM_DETAIL:'チーム詳細',
    SMALL:'小',
    SMALLEST:'最小',
    SORT_ORDER:'メッセージ表示順',
    START_SHALLWIN:'Shallwinを開始',
    SUCH_MESSAGE_NOT_FOUND:'メッセージが見つかりません',
    TEAMS:'チーム',
    TEAM_FILTER:'チームフィルタ',
    TEL_NO:'電話番号',
    TELEPATH_UPDATED:'テレパスがアップデートされました。新しいバージョンは次回起動時に有効になります',
    THEME:'テーマ',
    THREAD:'スレッド',
    TOGGLE_MENU:'このメニュー表示を切替',
    TOO_SHORT_PASSWORD:'パスワードが短すぎます',
    UNREAD_MESSAGE:'%s 件の未読',
    UNREAD_NOT_EXISTS:'未読はありません',
    UNSELECT_AFTER_SEND:'送信後宛先を全解除',
    UNSELECT_ALL:'全チーム選択解除',
    UNINSTALL:'アンインストール',
    UPDATE:'テレパスをアップデート',
    PASS_CONFIRM_NOT_MATCH :'パスワードと確認パスワードが一致していません',
    USER_ICON:'アイコン'
  }
}